### ISSUE TITLE
Playlists with directory characters cause a crash 

### ISSUE THREAD

**Issue by gregscds** [stu247/spl#2]
Great utility, I pulled out 1000 tracks worth of playlists--thanks!  I noticed though that If you export a playlist with a directory character like "/" the program crashes.  Example using "Foo/Bar" as the playlist name:

Traceback (most recent call last):
  File "spl.py", line 429, in <module>
    spl = SPL()
  File "spl.py", line 377, in **init**
    self.exportPl(speaker, pl, args.force, args.exportDetails)
  File "spl.py", line 103, in exportPl
    with codecs.open(fileName, 'w', 'utf-8') as fp:
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/codecs.py", line 896, in open
    file = **builtin**.open(filename, mode, buffering)
IOError: [Errno 2] No such file or directory: u'Foo/Bar.xspf'

This is looking for a subdirectory name "Foo" to write the file "Bar.xspf" in and that's failing because Foo doesn't exist.  I suspect "\" will also be a problem given how Python also supports Windows-style directory names.

There are a few ways this might be handled:
1. Document the problem in the help message as a limitation and don't change anything else.
2. Catch the problem and display a proper error message.  (Near line 100 where "Error: file already exists" is already caught)
3. Rename the exported playlist automatically with a new name, perhaps just putting a space there instead.  This is user friendly but may cause confusion later about the file name, rather than forcing the user to cope with it now.
4. Do nothing and consider this issue being open as enough warning for people.

I would vote for #2 myself if you wanted to work on this, but UI is a very subjective thing.

**Comment by stu247** [comment]
Thanks for reporting that.  spl now maps / or \ to _ and catches any other IOError.
