### ISSUE TITLE
General problem by execution

### ISSUE THREAD

**Issue by msanecki** [stu247/spl#3]
Here you have traceback from my first execution. I've just downloaded the latest version of the spl and executed it without any param.  
Python version: 2.7.12

Traceback (most recent call last):
  File "C:\Users\User\Downloads\spl\spl.py", line 446, in <module>
    spl = SPL()
  File "C:\Users\User\Downloads\spl\spl.py", line 260, in __init__
    zones = soco.discover()
  File "C:\Python27\lib\site-packages\soco\discovery.py", line 123, in discover
    list(s.getsockname()[0] for s in _sockets))
  File "C:\Python27\lib\site-packages\soco\discovery.py", line 123, in <genexpr>
    list(s.getsockname()[0] for s in _sockets))
  File "C:\Python27\lib\socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 10022] Wrong argument was given. (my translation)

**Comment by stu247** [comment]
This looks like an issue with SoCo.  It is independent of spl.  I have written a SoCo issue for it (https://github.com/SoCo/SoCo/issues/449).

**Comment by msanecki** [comment]
So the problem cannot be reproduced with the SoCo development version 0.11.1. I have built and install it an all looks almost fine.

What I get now is:
C:\Users\User\Downloads\spl>spl.py
Error: cannot communicate with the speaker.

Any hint?

Ok it got working by the second try...

**Comment by stu247** [comment]
I have seen sometimes SoCo does not work first time, but then does with second attempt.

A work around for the original issue of socket.error when using SoCo 0.12 is to specify the IP interface with -I option.  For example `python spl.py -I 192.168.1.23`
