### ISSUE TITLE
Error: discover returned no speakers

### ISSUE THREAD

**Issue by kibadi** [stu247/spl#7]
Hi,

after one of the recent Sonos updates spl.py cannot discover the Sonos speakers anymore although it worked before in the same environment (Win 10, python 2.7).

```
>python spl.py -X
Error: discover returned no speakers.
```

Other users in the Sonos community report the same issue 
https://en.community.sonos.com/controllers-software-228995/feature-request-export-and-import-sonos-playlists-5027121/index9.html#post16326276

Supplying either speaker IP does also not work:
```
>python spl.py -X -I 192.168.123.123

Traceback (most recent call last):
  File "spl.py", line 408, in <module>
    spl = SPL()
  File "spl.py", line 236, in __init__
    zones = soco.discover(interface_addr=args.interface)
  File "C:\Python27\lib\site-packages\soco\discovery.py", line 99, in discover
    _sockets.append(create_socket(interface_addr))
  File "C:\Python27\lib\site-packages\soco\discovery.py", line 77, in create_socket
    socket.inet_aton(interface_addr))
  File "C:\Python27\lib\socket.py", line 222, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 10049] The requested address is not valid in this context  [translated from German]
```

If you find the time and motivation to support this project of yours further, I would be grateful if you could take a look at this issue.

Many thanks,
Stefan

**Comment by stu247** [comment]
Sonos changed their interface in 10.1 which broke the SoCo's discovery() API.  See [https://github.com/SoCo/SoCo/releases/tag/v0.17](url).  Spl uses SoCo to interact with Sonos speakers.  You will need to upgrade your SoCo module to 0.17.  I have tested spl with SoCo 0.17 and it works fine.

**Comment by kibadi** [comment]
@stu247 Thank you for the immediate response! I will update SoCo to the latest version then.
