### ISSUE TITLE
Exporting and Importing playlist in Sonos show only albumart, No Artist or Trackname.

### ISSUE THREAD

**Issue by roelbroersma** [stu247/spl#8]
![image](https://user-images.githubusercontent.com/7059138/59552945-ce8cb780-8f8d-11e9-855d-f0b5557baf77.png)

When exporting an playlist to a file.   Then deleting the playlist in Sonos.   Then importing the playlist from file to Sonos,    now it shows no Track and Artist info anymore.. however.. the number is playing/working...  

Running Sonos 10.2   / Version: 10.2 (build 50165071)

Here is the XML of the export/import:

```
<?xml version="1.0" encoding="UTF-8"?>
<playlist version="1" xmlns="http://xspf.org/ns/0/">
 <title>xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx</title>
 <trackList>
  <track>
   <creator>Jacob Banks</creator>
   <title>Chainsmoking</title>
   <album>Village</album>
   <location>x-sonos-spotify:spotify%3atrack%3a1EZfCViOJ9XKFbwX8FkZUF?sid=12&amp;flags=8224&amp;sn=8</location>
  </track>
  <track>
   <creator>KALEO</creator>
   <title>Way Down We Go</title>
   <album>A/B</album>
   <location>x-sonos-spotify:spotify%3atrack%3a0y1QJc3SJVPKJ1OvFmFqe6?sid=12&amp;flags=8224&amp;sn=8</location>
  </track>
  <track>
   <creator>Leonard Cohen</creator>
   <title>You Want It Darker</title>
   <album>You Want It Darker</album>
   <location>x-sonos-spotify:spotify%3atrack%3a5zb7npjQqoJ7Kcpq4yD9qn?sid=12&amp;flags=8224&amp;sn=8</location>
  </track>
  <track>
   <creator>Ben Pearce</creator>
   <title>What I Might Do - Radio Edit</title>
   <album>What I Might Do</album>
   <location>x-sonos-spotify:spotify%3atrack%3a3yRKb8izxmUPmyKwX2mZ6a?sid=12&amp;flags=8224&amp;sn=8</location>
  </track>
 </trackList>
</playlist>

```

**Comment by stu247** [comment]
I tried to get import of streaming tracks to work a couple years ago and was not able to.  The import only uses the location tag in the XSPF file.  The other tags are only there to identify the track for someone looking at the XSPF file. SoCo or Sonos correctly determines the metadata when the location is a file, but not when the location is a streaming track.  

I have added a section to the README to document this limitation.
